resources:
  - name: global_state
    type: state
    
jobs:  
  - name: task_runner
    type: runSh
    steps:
      - IN: global_state
        switch: off
      - TASK:
        - script: echo 'This is task in old format'
        - script: ls -alh
        - script: env
        - script: df -h
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'
    flags:
      - runsh
